---
- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../vars/common-vars.asb.yml

  tasks:

    - name: "Deploy CloudFormation stack {{ local_stack_name }}"
      amazon.aws.cloudformation:
        stack_name: "{{ local_stack_name }}"
        state: present
        region: "{{ local_region_name }}"
        profile: "{{ local_account_name }}"
        template: "templates/buckets-use1.cfn.yml"
        tags: "{{ local_aws_tags }}"
        template_parameters:
          SsmAssetsBucketNameKey: "{{ ssm_assets_bucket_name_key }}"
          SsmLogsBucketNameKey: "{{ ssm_logs_bucket_name_key }}"
          AwsElbAccountId: "{{ aws_config[local_region_name].elb_account_id }}"
      vars:
        local_account: "{{ aws_accounts.labs }}"
        local_account_name: "{{ local_account.account_name }}"
        local_account_code: "{{ local_account.account_code }}"
        local_region_name: "{{ default_aws_region }}"
        local_region_code: "{{ default_aws_region_code }}"
        local_stack_name: "{{ local_account_code }}-{{ local_region_code }}-{{ application }}-buckets"
        local_aws_tags:
          Application: "{{ application }}"
          Environment: "{{ local_account.environment }}"
          Name: "{{ local_stack_name }}"

    - name: "Deploy CloudFormation stack {{ local_stack_name }}"
      amazon.aws.cloudformation:
        stack_name: "{{ local_stack_name }}"
        state: present
        region: "{{ local_region_name }}"
        profile: "{{ local_account_name }}"
        template: "templates/codecommit.cfn.yml"
        tags: "{{ local_aws_tags }}"
        template_parameters:
          AppRepoName: "{{ repo_app }}"
          InfraRepoName: "{{ repo_infra }}"
      vars:
        local_account: "{{ aws_accounts.labs }}"
        local_account_name: "{{ local_account.account_name }}"
        local_account_code: "{{ local_account.account_code }}"
        local_region_name: "{{ default_aws_region }}"
        local_region_code: "{{ default_aws_region_code }}"
        local_stack_name: "{{ local_account_code }}-{{ local_region_code }}-{{ application }}-codecommit"
        local_aws_tags:
          Application: "{{ application }}"
          Environment: "{{ local_account.environment }}"
          Name: "{{ local_stack_name }}"
