Parameters:

  AssetsBucketName:
    Type: String

Resources:

  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AssetsBucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Ref AssetsBucketName

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${AssetsBucketName}
              - !Sub arn:aws:s3:::${AssetsBucketName}/*
            Condition:
              Bool:
                'aws:SecureTransport': false
          - Sid: DenyDeleteObjectVersion
            Effect: Deny
            Principal: '*'
            Action: s3:DeleteObjectVersion
            Resource: !Sub arn:aws:s3:::${AssetsBucketName}/*
