Parameters:

  ApplicationRepoName:
    Type: String

Resources:

  ApplicationRepo:
    Type: AWS::CodeCommit::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: !Ref ApplicationRepoName
