Parameters:

  ApplicationDns:
    Description: Application DNS
    Type: String

Resources:

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        PriceClass: PriceClass_100
        HttpVersion: http2
        Origins:
          - Id: Application
            DomainName: !Ref ApplicationDns
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginReadTimeout: 60
        Enabled: true
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCachingMinTTL: 0
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
        DefaultCacheBehavior:
          TargetOriginId: Application
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Headers:
              - Host
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0

