apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: in-cluster-apps
  sources:
    - repoURL: 'https://aws.github.io/eks-charts'
      targetRevision: 1.6.1
      chart: aws-load-balancer-controller
      helm:
        valueFiles:
          - $values/config/aws-alb-controller/values.override.yaml
    - repoURL: {{ .Values.spec.source.repoURL }}
      targetRevision: {{ .Values.spec.source.targetRevision }}
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
