AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:

  LoggerCorretto:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: awslambdajava-logger
      Handler: cloud.spikeseed.Handler
      Runtime: java11
      CodeUri: ../../lambdas/logger/target/java-logger.zip
      MemorySize: 256
      Timeout: 15
