apiVersion: v2
description: A place for all the Kubernetes resources which don't already have a home
name: raw
version: v0.2.5
kubeVersion: ">=1.16.0-0"
home: https://github.com/itscontained/charts/blob/master/itscontained/raw
keywords:
  - raw
  - incubator
  - incubator-raw
sources:
  - https://github.com/helm/charts/blob/master/incubator/raw
maintainers:
  - name: DirtyCajunRice
    email: nick@cajun.pro