Parameters:

  AssetsBucketName:
    Type: String
  LogsBucketName:
    Type: String

Resources:

  #================
  # Assets
  #================

  AssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref AssetsBucketName
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Name
          Value: !Ref AssetsBucketName

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AssetsBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${AssetsBucketName}
              - !Sub arn:aws:s3:::${AssetsBucketName}/*
            Condition:
              Bool:
                'aws:SecureTransport': false
          - Sid: DenyDeleteObjectVersion
            Effect: Deny
            Principal: '*'
            Action: s3:DeleteObjectVersion
            Resource: !Sub arn:aws:s3:::${AssetsBucketName}/*

  #================
  # Logs
  #================

  LogsBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref LogsBucketName
      AccessControl: LogDeliveryWrite
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Prefix: /
            Status: Enabled
            Transitions:
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 30
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Name
          Value: !Ref LogsBucketName

  LogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LogsBucketName
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: '*'
            Action: s3:*
            Resource:
              - !Sub arn:aws:s3:::${LogsBucketName}
              - !Sub arn:aws:s3:::${LogsBucketName}/*
            Condition:
              Bool:
                'aws:SecureTransport': false
          - Sid: DenyDeleteObjectVersion
            Effect: Deny
            Principal: '*'
            Action: s3:DeleteObjectVersion
            Resource: !Sub arn:aws:s3:::${LogsBucketName}/*
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:GetBucketAcl
            Resource: !Sub arn:aws:s3:::${LogsBucketName}
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:PutObject
            Resource:
            - !Sub arn:aws:s3:::${LogsBucketName}/vpcquerylogs/AWSLogs/${AWS::AccountId}/*
            - !Sub arn:aws:s3:::${LogsBucketName}/vpcflowlogs/AWSLogs/${AWS::AccountId}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
