---
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    pbk_account: "{{ aws_accounts.labs }}"
    pbk_account_name: "{{ pbk_account.account_name }}"
    pbk_account_code: "{{ pbk_account.account_code }}"
    pbk_account_env: "{{ pbk_account.environment }}"

  vars_files:
    - ../vars/common-vars.asb.yml

  tasks:

    # ======================================================================================================================
    # VPC
    # ======================================================================================================================

    - name: "Deploy CloudFormation stack {{ local_stack_name }}"
      amazon.aws.cloudformation:
        stack_name: "{{ local_stack_name }}"
        state: present
        region: "{{ local_region_name }}"
        profile: "{{ pbk_account_name }}"
        template: "templates/vpc.cfn.yml"
        tags: "{{ local_aws_tags }}"
        template_parameters:
          AccountName: "{{ pbk_account_name }}"
          AccountCode: "{{ pbk_account_code }}"
          RegionCode: "{{ local_region_code }}"
          Application: "{{ application }}"
          VpcCidr: "{{ pbk_account.vpc_cidr }}"
          PublicSubnetCidrAz1: "{{ pbk_account.web_public_subnet_az1_cidr }}"
          PublicSubnetCidrAz2: "{{ pbk_account.web_public_subnet_az2_cidr }}"
          AppPrivateSubnetCidrAz1: "{{ pbk_account.app_private_subnet_az1_cidr }}"
          AppPrivateSubnetCidrAz2: "{{ pbk_account.app_private_subnet_az2_cidr }}"
          SsmVpcIdKey: "{{ ssm_vpc_id_key  }}"
          SsmPublicSubnetsKey: "{{ ssm_web_public_subnets_id_key }}"
          SsmAppPrivateSubnetsKey: "{{ ssm_app_private_subnets_id_key }}"
      vars:
        local_region_name: "{{ default_aws_region }}"
        local_region_code: "{{ default_aws_region_code }}"
        local_stack_name: "{{ pbk_account_code }}-{{ local_region_code }}-{{ application }}-vpc"
        local_aws_tags:
          Application: "{{ application }}"
          Environment: "{{ pbk_account_env }}"
          Name: "{{ local_stack_name }}"
      tags:
        - vpc
